server:
  port: 8080

spring:
  mvc:
    jsp:
      el-expression-prefix=${elExpressionPrefix:=${}}
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ssm
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 10

  data:
    redis:
      host: 127.0.0.1  # 地址
      port: 6379  # 端口号
      password:
      database: 3  # 数据库索引（默认为0）
      timeout: 1800000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1  # 最大阻塞等待时间（负数表示没有限制）
          max-idle: 5  # 连接池中最大空闲连接
          min-idle: 0  # 连接池中最小空闲连接

